# Feature flags configuration
# This file controls which features are enabled/disabled in the application

features:
  # Dataset feature - controls access to recipe dataset functionality
  dataset:
    enabled: false
    description: "Enable/disable access to the recipe dataset and related features"
  
  # AI Suggestions feature
  suggestions:
    enabled: true
    description: "Enable/disable AI-powered recipe suggestions using Gemini"
  
  # RAG AI feature
  rag:
    enabled: true
    description: "Enable/disable RAG-based recipe recommendations"
  
  # Weekly planner feature
  weeklyPlanner:
    enabled: true
    description: "Enable/disable weekly meal planning functionality"

# API configuration
api:
  # Rate limiting for API calls
  rateLimit:
    enabled: true
    requestsPerMinute: 60
  
  # Caching configuration
  cache:
    enabled: true
    ttlMinutes: 30

# UI configuration
ui:
  # Debug mode for development
  debug: false
  
  # Analytics tracking
  analytics:
    enabled: false